
version: '3'

services:
  db:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  client:
    image: node:16
    container_name: client
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - REACT_APP_BASE_URL_DEVELOPMENT=http://127.0.0.1:5000/api/v1
      - ESLINT_NO_DEV_ERRORS=true
    tty: true
    stdin_open: true
    working_dir: /usr/src/cars-management/app
    volumes:
      - ./app:/usr/src/cars-management/app
    restart: always
    command: yarn serve
  server:
    image: node:16
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://mongo:27017/cars-managements
    working_dir: /usr/src/cars-management/server
    volumes:
      - ./server:/usr/src/cars-management/server
    restart: always
    tty: true
    stdin_open: true
    command: yarn start