
version: '3'

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    volumes:
      - 'db:/data/db'
    networks:
      - backend
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - REACT_APP_API_BASE_URL=http://server:$NODE_DOCKER_PORT/api/v1
      - ESLINT_NO_DEV_ERRORS=true
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    depends_on:
      - server
    tty: true
    stdin_open: true
    networks:
      - frontend
    command: yarn prod
  server: 
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongo
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    networks:
      - backend
      - frontend
    tty: true
    stdin_open: true
    command: yarn start

volumes: 
  db:

networks:
  backend:
  frontend: