
version: '3'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    # networks:
    #   - cars-management
  client:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - API_URL=http://127.0.0.1:$REACT_LOCAL_PORT/api/v1
    ports:
      - 8080:8080
    links:
      - server:server
    # networks: 
    #   - cars-management
    depends_on:
      - server
    tty: true
    stdin_open: true
    # volumes:
    #   - ./app:/usr/src/cars-management/app
    #   - /usr/src/cars-management/app/node_modules
    command: yarn dev
  server: 
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # networks:
    #   - cars-management
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    tty: true
    stdin_open: true
    # volumes:
    #   - ./server:/usr/src/cars-management/server
    #   - /usr/src/cars-management/server/node_modules
    command: yarn start

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - /usr/src/cars-management/app/build:/usr/share/nginx/html
    ports:
      - 8000:8000
      - 443:443

# networks:
#   cars-management:
#     driver: bridge