
version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    networks:
      - server
  client:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - server
    depends_on:
      - server
    environment:
      - REACT_APP_API_BASE_URL=http://server:$NODE_DOCKER_PORT/api/v1
      - ESLINT_NO_DEV_ERRORS=true
    tty: true
    stdin_open: true
    command: yarn prod
  server: 
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - client
      - server
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    tty: true
    stdin_open: true
    command: yarn start

networks:
  client:
  server: