
version: '3'

services:
  db:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  client:
    container_name: client
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - REACT_APP_BASE_URL_DEVELOPMENT=http://127.0.0.1:5000/api/v1
    command: yarn start
    stdin_open: true
    tty: true
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://mongo:27017/cars-managements
      - CLIENT=http://127.0.0.1:3000
    command: yarn start
