
version: '3'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
  client:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - API_URL=http://${HOST_IP_PROD}:$REACT_LOCAL_PORT/api/v1
    ports:
      - 80:8080
    links:
      - server:server
    depends_on:
      - server
    tty: true
    stdin_open: true
    command: yarn dev
  server: 
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    tty: true
    stdin_open: true
    command: yarn start
